name = "resume"
description = "A resume theme"
license = "MIT"
homepage = "https://github.com/Biorelaxa"
min_version = "0.11.0"
demo = "https://biorelaxa.github.io/"

compile_sass = true
generate_feeds = true

taxonomies = [
  { name = "tags", feed = true },
]

[extra]
first_name = "Shen"
last_name = "Hongyu"
address = "Harbin, China"
email = "peterluck2021@163.com"
favicon = "/favicon.ico"
avatar = "/media/avatar.png"

katex = false
show_about = true
show_skills = true
show_projects = true
show_opensource = true
show_publications = true
show_experience = true
show_education = true
show_blog = true

[author]
name = "Feng Yunlong"
homepage = "https://www.alongwy.top"

[original]
author =  "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
repo = "https://github.com/getzola/hyde"
