name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Zola
        run: |
          curl -sL https://github.com/getzola/zola/releases/download/v0.18.1/zola-v0.18.1-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C /usr/local/bin
      - name: Build
        run: zola build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public